name: Release

on:
  workflow_dispatch:

jobs:
  release:
    permissions:
      id-token: write
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Install Node.js LTS
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: pnpm
          registry-url: 'https://registry.npmjs.org'

#      - run: pnpx changelogithub
#        env:
#          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Install dependencies
        run: pnpm install

      - name: Build packages, examples and comparisons
        run: pnpm build

      - name: Set NPM config for provenance and auth
        run: |
          pnpm config set provenance true
          pnpm config set //registry.npmjs.org/:_authToken ${{secrets.NPM_TOKEN}}

      - name: Publish to NPM
        run: pnpm -r publish --access public --no-git-checks
